// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysiysorvenesdhzotlab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzaXlzb3J2ZW5lc2Roem90bGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjI0MTAsImV4cCI6MjA3Mjk5ODQxMH0.fFuaB2gxXDaTa-Azk_M0OQLHuyDLEzlqHBG-NARPbgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});